name: pokedex
description: "New pokedex project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  animation_wrappers: ^3.0.0
  shimmer: ^3.0.0
  sizer_pro: ^2.2.0
  flutter_bounceable: ^1.2.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
